[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_ENV = "production"

# Main branch - Production
[context.production]
  publish = "dist"
  command = "npm run build"
  [context.production.environment]
    NODE_ENV = "production"
    VITE_API_BASE_URL = "https://hzmbackandveritabani-production-c660.up.railway.app/api/v1"
    VITE_APP_TITLE = "HZMSoft Database Pro"

# Development branch - Test/Staging
[context.development]
  publish = "dist"
  command = "npm run build"
  [context.development.environment]
    NODE_ENV = "development"
    VITE_API_BASE_URL = "https://hzmbackandveritabani-production-c660.up.railway.app/api/v1"
    VITE_APP_TITLE = "HZMSoft Database Pro - TEST ORTAMI"

# Branch deployments
[context.branch-deploy]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:;" 